---
# tasks file for ansible-role-cvmfs
- name: Import the CVMFS rpm gpg key
  ansible.builtin.rpm_key:
    key: "https://cvmrepo.web.cern.ch/cvmrepo/yum/RPM-GPG-KEY-CernVM-2048"
    state: present
  register: cvmfs_cernrepokey

- name: Install cvmfs-release
  ansible.builtin.dnf:
    name: "https://cvmrepo.web.cern.ch/cvmrepo/yum/cvmfs-release-latest.noarch.rpm"
    state: present

- name: Install CVMFS client EL9
  ansible.builtin.dnf:
    name: ["cvmfs", "cvmfs-config-default", "autofs"]
    state: present
  when: ansible_facts["distribution_major_version"] == "9"

- name: Install CVMFS client EL10
  ansible.builtin.dnf:
    name: ["cvmfs", "cvmfs-config-default", "autofs"]
    state: present
  when: ansible_facts["distribution_major_version"] == "10"
